### ISSUE TITLE
problem das not show in web browser

### ISSUE THREAD

**Issue by xorgxx** [NAYZO/NzoFileDownloaderBundle#2]
hi thank for this bundle.

i have small problem, i try to get view strait in my browser but alway it gave me to download ?!

i my code i have this : 

```
return $this->get('nzo_file_downloader')->downloadFile('myfolder/myfile.txt')
```

of cause download working perfect.

thank for your help

**Comment by nayzo** [comment]
Nice catch,
Fixed: Now you can use the **readFile** new function. see the README.md file.
Update your composer.json by upgrading the bundle to the "~2.0" version and do a composer update and you'ill be good to go. :+1:
